import { useEffect, useState } from 'react'
import type { CharacterMemory, WorldBookUserPlaceholderBinding } from '../newFriendsPersona/types'
import { loadAccountsBundle } from '../wechatAccountPersistence'
import { countWorldBookUserPlaceholderSlots } from '../worldBookUserPlaceholderBindings'
import {
  bindingFromMemoryEditorIdentityOption,
  type MemoryEditorIdentityOption,
} from './memoryEditorCharacterIdentityOptions'
import {
  resolveMemoryEntrySourceLineLabel,
  resolveMemoryUserBindingLabels,
} from './memoryArchiveSourceLabel'

export function MemoryEditorBindingSummary({
  open,
  draft,
  editorInsertLabel,
  identityOptions = [],
  userBindings,
  onUserBindingsChange,
  section = 'all',
}: {
  open: boolean
  draft: Pick<
    CharacterMemory,
    | 'content'
    | 'sourceWechatAccountId'
    | 'sourceSessionPlayerIdentityId'
    | 'userPlaceholderBindings'
    | 'memoryScope'
  > | null
  /** 当前选中的插入/补绑身份（微信昵称 · 扮演身份） */
  editorInsertLabel?: string | null
  identityOptions?: MemoryEditorIdentityOption[]
  userBindings?: WorldBookUserPlaceholderBinding[]
  onUserBindingsChange?: (next: WorldBookUserPlaceholderBinding[]) => void
  /** identity：写入来源与默认插入身份；user：{{user}} 槽位；all：合并（兼容旧用法） */
  section?: 'identity' | 'user' | 'all'
}) {
  const [sourceLineLabel, setSourceLineLabel] = useState<string | null>(null)
  const [userBindingLabels, setUserBindingLabels] = useState<string[]>([])

  useEffect(() => {
    if (!open || !draft) {
      setSourceLineLabel(null)
      setUserBindingLabels([])
      return
    }
    let cancelled = false
    void (async () => {
      const bundle = await loadAccountsBundle()
      const pseudo: CharacterMemory = {
        id: '__draft__',
        characterId: '__draft__',
        content: draft.content,
        createdAt: 0,
        updatedAt: 0,
        isAutoGenerated: false,
        memoryScope: draft.memoryScope,
        sourceWechatAccountId: draft.sourceWechatAccountId,
        sourceSessionPlayerIdentityId: draft.sourceSessionPlayerIdentityId,
        userPlaceholderBindings: draft.userPlaceholderBindings,
      }
      const [src, users] = await Promise.all([
        resolveMemoryEntrySourceLineLabel(pseudo, bundle),
        resolveMemoryUserBindingLabels(pseudo, bundle),
      ])
      if (!cancelled) {
        setSourceLineLabel(src ?? null)
        setUserBindingLabels(users)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [open, draft])

  const slotCount = draft ? countWorldBookUserPlaceholderSlots(draft.content ?? '') : 0
  const canEditSlots =
    !!onUserBindingsChange &&
    identityOptions.length >= 2 &&
    slotCount > 0 &&
    !!userBindings

  const setSlotBinding = (index: number, opt: MemoryEditorIdentityOption) => {
    if (!onUserBindingsChange || !userBindings) return
    const next = [...userBindings]
    while (next.length < slotCount) {
      next.push({ wechatAccountId: '', playerIdentityId: '' })
    }
    next[index] = bindingFromMemoryEditorIdentityOption(opt)
    onUserBindingsChange(next.slice(0, slotCount))
  }

  if (!open) return null

  const showIdentity = section === 'all' || section === 'identity'
  const showUser = section === 'all' || section === 'user'
  const identityEmpty =
    !sourceLineLabel && !editorInsertLabel && identityOptions.length < 2
  const userEmpty = slotCount === 0 && !userBindingLabels.length

  if (section === 'identity' && identityEmpty) {
    return (
      <div className="rounded-2xl bg-gray-50/90 px-4 py-3.5">
        <p className="text-[11px] leading-relaxed text-gray-500">
          该角色档案仅关联一个微信马甲。插入 {'{{user}}'} 时将使用当前登录账号下的扮演身份；可在「正文与预览」中刻录后再保存。
        </p>
      </div>
    )
  }

  if (section === 'user' && userEmpty) {
    return (
      <div className="rounded-2xl bg-gray-50/90 px-4 py-3.5">
        <p className="text-[10px] tracking-[0.2em] uppercase text-gray-400">{'{{user}}'} 槽位</p>
        <p className="mt-2 text-[11px] leading-relaxed text-gray-500">
          正文中尚无 {'{{user}}'} 表达式。请先在「正文与预览」页点击「用户」插入，再回来为各槽位指定绑定马甲。
        </p>
      </div>
    )
  }

  if (section === 'all' && identityEmpty && userEmpty) return null

  const sectionTitle =
    section === 'identity'
      ? '写入来源与默认身份'
      : section === 'user'
        ? '{{user}} 表达式绑定'
        : '账号与身份绑定'

  return (
    <div className={section === 'all' ? 'mt-5 rounded-2xl bg-gray-50/90 px-4 py-3.5' : 'rounded-2xl bg-gray-50/90 px-4 py-3.5'}>
      <p className="text-[10px] tracking-[0.2em] uppercase text-gray-400">{sectionTitle}</p>
      {showIdentity && editorInsertLabel && identityOptions.length < 2 ? (
        <div className="mt-2.5 rounded-xl bg-white/80 px-3 py-2.5">
          <p className="text-[10px] text-gray-400">当前编辑 · 插入 {'{{user}}'} 将绑定到</p>
          <p className="mt-0.5 text-[13px] font-semibold text-gray-900">{editorInsertLabel}</p>
        </div>
      ) : null}
      {showIdentity && sourceLineLabel ? (
        <div className={editorInsertLabel ? 'mt-3' : 'mt-2.5'}>
          <p className="text-[10px] text-gray-400">本条记忆写入来源（只读，不因你换号编辑而改变）</p>
          <p className="mt-0.5 text-[13px] font-medium text-gray-700">{sourceLineLabel}</p>
        </div>
      ) : null}
      {showIdentity && section === 'identity' && identityOptions.length >= 2 ? (
        <p className="mt-3 text-[11px] leading-relaxed text-gray-500">
          该角色关联了多个马甲。请在上方列表选择默认身份；新插入的 {'{{user}}'} 与未绑定槽位保存时将按此补全。
        </p>
      ) : null}
      {showUser && userBindingLabels.length ? (
        <div className={showIdentity && (sourceLineLabel || editorInsertLabel) ? 'mt-3' : 'mt-2.5'}>
          <p className="text-[10px] text-gray-400">正文中 {'{{user}}'} 各槽位当前绑定</p>
          <ul className="mt-1.5 space-y-2">
            {userBindingLabels.map((lbl, i) => (
              <li key={`${i}-${lbl}`} className="text-[12px] leading-relaxed text-gray-700">
                <span className="mr-1.5 font-mono text-[10px] text-gray-400">第 {i + 1} 处</span>
                {canEditSlots ? (
                  <select
                    value={
                      identityOptions.find(
                        (o) =>
                          o.ctx.wechatAccountId === userBindings?.[i]?.wechatAccountId?.trim() &&
                          o.ctx.playerIdentityId === userBindings?.[i]?.playerIdentityId?.trim(),
                      )?.key ??
                      identityOptions.find((o) => o.label === lbl)?.key ??
                      ''
                    }
                    onChange={(e) => {
                      const opt = identityOptions.find((o) => o.key === e.target.value)
                      if (opt) setSlotBinding(i, opt)
                    }}
                    className="mt-1 block w-full rounded-lg border-0 bg-white/90 px-2 py-1.5 text-[12px] text-gray-900 outline-none ring-1 ring-gray-200/80"
                  >
                    {identityOptions.map((o) => (
                      <option key={o.key} value={o.key}>
                        {o.label}
                      </option>
                    ))}
                  </select>
                ) : (
                  lbl
                )}
              </li>
            ))}
          </ul>
          <p className="mt-2 text-[11px] leading-relaxed text-gray-400">
            {canEditSlots
              ? '可为每一处单独指定马甲；新插入的「用户」或尚未绑定的槽位，保存时会按「绑定身份」页所选身份补全。'
              : '已有槽位保留原绑定；新插入的「用户」或尚未绑定的槽位，保存时会按「绑定身份」页所选身份补全。'}
          </p>
        </div>
      ) : null}
      {showUser && section === 'user' && slotCount > 0 && !userBindingLabels.length ? (
        <p className="mt-2 text-[11px] leading-relaxed text-gray-500">
          检测到 {slotCount} 处 {'{{user}}'}，保存前将按「绑定身份」页所选马甲自动补绑。
        </p>
      ) : null}
    </div>
  )
}
