import type { ApiConfig } from '../api/types'
import { personaDb, pullPhoneKvWithLocalStorageLegacy } from './newFriendsPersona/idb'
import { requestUnifiedMemorySummary, type ChatTranscriptTurn } from './wechatChatAi'

const DATING_ARCHIVES_KV = 'wechat-dating-archives-v1'

export type DatingPlotSnapshotItem = {
  type: string
  content: string
  timestamp?: number
}

function extractPlotsFromArchives(raw: unknown, characterId: string): DatingPlotSnapshotItem[] {
  if (!raw || typeof raw !== 'object') return []
  const entry = (raw as Record<string, unknown>)[characterId]
  if (!entry || typeof entry !== 'object') return []
  const plots = (entry as { plots?: unknown }).plots
  if (!Array.isArray(plots)) return []
  const out: DatingPlotSnapshotItem[] = []
  for (const p of plots) {
    if (!p || typeof p !== 'object') continue
    const o = p as Record<string, unknown>
    const type = typeof o.type === 'string' ? o.type : ''
    const content = typeof o.content === 'string' ? o.content : ''
    const timestamp =
      typeof o.timestamp === 'number' && Number.isFinite(o.timestamp) ? o.timestamp : 1
    if (!content.trim()) continue
    if (type !== 'player' && type !== 'ai') continue
    out.push({ type, content, timestamp })
  }
  return out
}

async function loadDatingPlotsFromKv(characterId: string): Promise<DatingPlotSnapshotItem[]> {
  const cid = characterId.trim()
  if (!cid) return []
  let raw: unknown = await personaDb.getPhoneKv(DATING_ARCHIVES_KV)
  if (raw == null) {
    raw = await pullPhoneKvWithLocalStorageLegacy(DATING_ARCHIVES_KV, [DATING_ARCHIVES_KV])
  }
  return extractPlotsFromArchives(raw, cid)
}

/**
 * 在「已达到自动总结间隔」之后调用（调用方须先 `bumpMemoryAiRoundCount` 且得到 `shouldSummarize: true`）。
 * 合并未游标覆盖的微信消息与约会线下剧情，写入一条长期记忆，并分别推进两条游标。
 * 若线上与线下均无新材料，则回滚计数，避免白消耗一次间隔。
 */
export async function runUnifiedAutoMemorySummaryAfterThreshold(params: {
  apiConfig: ApiConfig | null
  conversationKey: string
  characterId: string
  characterRealName: string
  /** 约会页刚写入、KV 可能尚未同步时，传入当前完整 plots */
  datingPlotsSnapshot?: DatingPlotSnapshotItem[] | null
}): Promise<void> {
  const cid = params.characterId.trim()
  const ck = params.conversationKey.trim()
  if (!cid || !ck) return

  const cursorTs = await personaDb.getMemorySummaryCursorTimestamp(ck)
  const fromTs = (cursorTs ?? 0) + 1
  const chunkMessages = await personaDb.listWeChatChatMessagesFromTimestampAsc({
    conversationKey: ck,
    fromTimestampInclusive: fromTs,
    limit: 500,
  })

  const onlineTranscript: ChatTranscriptTurn[] = chunkMessages.flatMap((m) => {
    const text = String(m.content || '').trim()
    if (!text) return []
    const turn: ChatTranscriptTurn = {
      id: m.id,
      from: m.type === 'player' ? 'self' : 'other',
      text,
    }
    return [turn]
  })

  const datingCursor = await personaDb.getDatingPlotSummaryCursor(cid)
  const dMin = datingCursor ?? 0

  let plotsSource: DatingPlotSnapshotItem[] =
    params.datingPlotsSnapshot && params.datingPlotsSnapshot.length > 0
      ? params.datingPlotsSnapshot
      : await loadDatingPlotsFromKv(cid)

  const offlinePlots = plotsSource
    .filter((p) => {
      const ts =
        typeof p.timestamp === 'number' && Number.isFinite(p.timestamp) ? p.timestamp : 1
      return ts > dMin
    })
    .sort((a, b) => (a.timestamp ?? 1) - (b.timestamp ?? 1))

  const peer = params.characterRealName.trim() || '对方'
  const offlineLines: string[] = []
  for (const p of offlinePlots) {
    const t = String(p.content || '').trim()
    if (!t) continue
    if (p.type === 'player') offlineLines.push(`我：${t}`)
    else offlineLines.push(`${peer}：${t}`)
  }
  const offlineBlock = offlineLines.join('\n')

  const hadOnline = onlineTranscript.length > 0
  const hadOffline = offlineBlock.trim().length > 0

  if (!hadOnline && !hadOffline) {
    await personaDb.rollbackMemoryAiRoundCountForRetry(ck)
    return
  }

  const summary = await requestUnifiedMemorySummary({
    apiConfig: params.apiConfig,
    onlineTranscript,
    offlineTextBlock: hadOffline ? offlineBlock : '',
  })

  let trimmed = summary.trim().slice(0, 2000)
  if (!trimmed) {
    await personaDb.rollbackMemoryAiRoundCountForRetry(ck)
    return
  }

  const tagPrefix =
    `${hadOnline ? '[线上]' : ''}${hadOffline ? '[线下]' : ''}${hadOnline || hadOffline ? ' ' : ''}`
  trimmed = tagPrefix + trimmed

  const now = Date.now()
  await personaDb.upsertCharacterMemory({
    id: `mem-${now}-${Math.random().toString(36).slice(2, 9)}`,
    characterId: cid,
    content: trimmed,
    createdAt: now,
    updatedAt: now,
    isAutoGenerated: true,
  })

  if (hadOnline && chunkMessages.length) {
    const latestTs = chunkMessages[chunkMessages.length - 1]!.timestamp
    if (typeof latestTs === 'number' && Number.isFinite(latestTs)) {
      await personaDb.setMemorySummaryCursorTimestamp(ck, latestTs)
    }
  }

  if (hadOffline && offlinePlots.length) {
    const maxPlotTs = Math.max(
      ...offlinePlots.map((p) =>
        typeof p.timestamp === 'number' && Number.isFinite(p.timestamp) ? p.timestamp : 1,
      ),
    )
    if (maxPlotTs > 0) {
      await personaDb.setDatingPlotSummaryCursor(cid, maxPlotTs)
    }
  }
}
