import type { ApiConfig } from '../api/types'
import { findGroupMember } from './groupChatUtils'
import { personaDb, pullPhoneKvWithLocalStorageLegacy } from './newFriendsPersona/idb'
import type { GroupChatRow, GroupMember, WeChatChatMessage } from './newFriendsPersona/types'
import {
  requestGroupChatMemorySummary,
  requestUnifiedMemorySummary,
  type ChatTranscriptTurn,
} from './wechatChatAi'
import {
  groupMemoryBucketCharacterId,
  WECHAT_GROUP_BOT_CHARACTER_ID,
  WECHAT_GROUP_USER_CHAR_ID,
} from './wechatConversationKey'

const DATING_ARCHIVES_KV = 'wechat-dating-archives-v1'

export type DatingPlotSnapshotItem = {
  type: string
  content: string
  timestamp?: number
}

function extractPlotsFromArchives(raw: unknown, characterId: string): DatingPlotSnapshotItem[] {
  if (!raw || typeof raw !== 'object') return []
  const entry = (raw as Record<string, unknown>)[characterId]
  if (!entry || typeof entry !== 'object') return []
  const plots = (entry as { plots?: unknown }).plots
  if (!Array.isArray(plots)) return []
  const out: DatingPlotSnapshotItem[] = []
  for (const p of plots) {
    if (!p || typeof p !== 'object') continue
    const o = p as Record<string, unknown>
    const type = typeof o.type === 'string' ? o.type : ''
    const content = typeof o.content === 'string' ? o.content : ''
    const timestamp =
      typeof o.timestamp === 'number' && Number.isFinite(o.timestamp) ? o.timestamp : 1
    if (!content.trim()) continue
    if (type !== 'player' && type !== 'ai') continue
    out.push({ type, content, timestamp })
  }
  return out
}

async function loadDatingPlotsFromKv(characterId: string): Promise<DatingPlotSnapshotItem[]> {
  const cid = characterId.trim()
  if (!cid) return []
  let raw: unknown = await personaDb.getPhoneKv(DATING_ARCHIVES_KV)
  if (raw == null) {
    raw = await pullPhoneKvWithLocalStorageLegacy(DATING_ARCHIVES_KV, [DATING_ARCHIVES_KV])
  }
  return extractPlotsFromArchives(raw, cid)
}

/**
 * 在「已达到自动总结间隔」之后调用（调用方须先 `bumpMemoryAiRoundCount` 且得到 `shouldSummarize: true`）。
 * 合并未游标覆盖的微信消息与约会线下剧情，写入一条长期记忆，并分别推进两条游标。
 * 若线上与线下均无新材料，则回滚计数，避免白消耗一次间隔。
 */
export async function runUnifiedAutoMemorySummaryAfterThreshold(params: {
  apiConfig: ApiConfig | null
  conversationKey: string
  characterId: string
  characterRealName: string
  /** 约会页刚写入、KV 可能尚未同步时，传入当前完整 plots */
  datingPlotsSnapshot?: DatingPlotSnapshotItem[] | null
}): Promise<void> {
  const cid = params.characterId.trim()
  const ck = params.conversationKey.trim()
  if (!cid || !ck) return

  const cursorTs = await personaDb.getMemorySummaryCursorTimestamp(ck)
  const fromTs = (cursorTs ?? 0) + 1
  const chunkMessages = await personaDb.listWeChatChatMessagesFromTimestampAsc({
    conversationKey: ck,
    fromTimestampInclusive: fromTs,
    limit: 500,
  })

  const onlineTranscript: ChatTranscriptTurn[] = chunkMessages.flatMap((m) => {
    const text = String(m.content || '').trim()
    if (!text) return []
    const turn: ChatTranscriptTurn = {
      id: m.id,
      from: m.type === 'player' ? 'self' : 'other',
      text,
    }
    return [turn]
  })

  const datingCursor = await personaDb.getDatingPlotSummaryCursor(cid)
  const dMin = datingCursor ?? 0

  let plotsSource: DatingPlotSnapshotItem[] =
    params.datingPlotsSnapshot && params.datingPlotsSnapshot.length > 0
      ? params.datingPlotsSnapshot
      : await loadDatingPlotsFromKv(cid)

  const offlinePlots = plotsSource
    .filter((p) => {
      const ts =
        typeof p.timestamp === 'number' && Number.isFinite(p.timestamp) ? p.timestamp : 1
      return ts > dMin
    })
    .sort((a, b) => (a.timestamp ?? 1) - (b.timestamp ?? 1))

  const peer = params.characterRealName.trim() || '对方'
  const offlineLines: string[] = []
  for (const p of offlinePlots) {
    const t = String(p.content || '').trim()
    if (!t) continue
    if (p.type === 'player') offlineLines.push(`我：${t}`)
    else offlineLines.push(`${peer}：${t}`)
  }
  const offlineBlock = offlineLines.join('\n')

  const hadOnline = onlineTranscript.length > 0
  const hadOffline = offlineBlock.trim().length > 0

  if (!hadOnline && !hadOffline) {
    await personaDb.rollbackMemoryAiRoundCountForRetry(ck)
    return
  }

  const summary = await requestUnifiedMemorySummary({
    apiConfig: params.apiConfig,
    onlineTranscript,
    offlineTextBlock: hadOffline ? offlineBlock : '',
  })

  let trimmed = summary.trim().slice(0, 2000)
  if (!trimmed) {
    await personaDb.rollbackMemoryAiRoundCountForRetry(ck)
    return
  }

  const tagPrefix =
    `${hadOnline ? '[线上]' : ''}${hadOffline ? '[线下]' : ''}${hadOnline || hadOffline ? ' ' : ''}`
  trimmed = tagPrefix + trimmed

  const now = Date.now()
  await personaDb.upsertCharacterMemory({
    id: `mem-${now}-${Math.random().toString(36).slice(2, 9)}`,
    characterId: cid,
    content: trimmed,
    createdAt: now,
    updatedAt: now,
    isAutoGenerated: true,
  })

  if (hadOnline && chunkMessages.length) {
    const latestTs = chunkMessages[chunkMessages.length - 1]!.timestamp
    if (typeof latestTs === 'number' && Number.isFinite(latestTs)) {
      await personaDb.setMemorySummaryCursorTimestamp(ck, latestTs)
    }
  }

  if (hadOffline && offlinePlots.length) {
    const maxPlotTs = Math.max(
      ...offlinePlots.map((p) =>
        typeof p.timestamp === 'number' && Number.isFinite(p.timestamp) ? p.timestamp : 1,
      ),
    )
    if (maxPlotTs > 0) {
      await personaDb.setDatingPlotSummaryCursor(cid, maxPlotTs)
    }
  }
}

function buildGroupArchiveText(group: GroupChatRow | null): string {
  if (!group) return ''
  const lines: string[] = []
  lines.push(`群名：${group.name.trim() || '群聊'}`)
  const userGn = group.members.find((m) => m.charId === WECHAT_GROUP_USER_CHAR_ID)?.groupNickname?.trim()
  if (userGn) lines.push(`用户在本群的昵称：${userGn}`)
  const roleLabel = (r: GroupMember['role']) =>
    r === 'owner' ? '群主' : r === 'admin' ? '管理员' : '成员'
  const roster = group.members
    .map((m) => {
      const rl = roleLabel(m.role)
      const mute = m.isMuted ? '（禁言中）' : ''
      return `${(m.groupNickname || m.charId).trim()}（${rl}）${mute}`
    })
    .join('；')
  lines.push(`成员与身份：${roster}`)
  const ann = (group.announcement ?? '').trim()
  if (ann) {
    lines.push(`群公告：${ann.slice(0, 400)}${ann.length > 400 ? '…' : ''}`)
  }
  const muted = group.members.filter(
    (m) => m.isMuted && m.charId.trim() !== WECHAT_GROUP_USER_CHAR_ID,
  )
  if (muted.length) {
    lines.push(`当前被禁言的成员（不含系统占位）：${muted.map((m) => m.groupNickname).join('、')}`)
  }
  return lines.join('\n')
}

function chunkMessagesToGroupTranscript(
  chunkMessages: WeChatChatMessage[],
  group: GroupChatRow | null,
): ChatTranscriptTurn[] {
  const out: ChatTranscriptTurn[] = []
  for (const m of chunkMessages) {
    const fromSelf = m.type === 'player'
    let speakerLabel: string | undefined
    if (!fromSelf) {
      const cid = m.characterId.trim()
      if (cid === WECHAT_GROUP_BOT_CHARACTER_ID) speakerLabel = '群管家'
      else if (group) {
        const mem = findGroupMember(group, cid)
        speakerLabel = mem?.groupNickname?.trim() || cid.slice(0, 12)
      }
    }
    let text = String(m.content || '').trim()
    const ext = (m as { ext?: { mutedMessageVisibleToModeratorsOnly?: boolean } }).ext
    if (ext?.mutedMessageVisibleToModeratorsOnly === true) {
      const who = fromSelf ? '我' : speakerLabel || '群成员'
      text = `（${who}在禁言期间尝试发言；群内未展示原文）`
    } else if (m.isRecalled) {
      const who = fromSelf ? '我' : speakerLabel || '群成员'
      text = `（${who}撤回了一条消息）`
    } else if (m.voice) {
      const vt = m.voice.transcriptText?.trim() || text || '（语音）'
      const emo = m.voice.emotionLabel?.trim()
      text = emo ? `（语音，情绪：${emo}）${vt}` : `（语音）${vt}`
    } else if (m.images?.length && !text) {
      text = '（发送了图片）'
    } else if (m.redPacket) {
      if (!text) text = `（红包，约 ¥${m.redPacket.amountYuan}）`
    } else if (m.transfer && !text) {
      text = '（转账）'
    }
    if (!text) continue
    out.push({ id: m.id, from: fromSelf ? 'self' : 'other', text, speakerLabel })
  }
  return out
}

/**
 * 群聊：在达到自动总结阈值后调用（与私聊共用 `bumpMemoryAiRoundCount` / 会话游标）。
 * 将未游标群消息与当前群成员/禁言等快照合并总结，并为每位**真实角色成员**各写入一条相同内容的长期记忆（便于在记忆管理页按联系人查看）。
 */
export async function runGroupChatMemorySummaryAfterThreshold(params: {
  apiConfig: ApiConfig | null
  conversationKey: string
  groupId: string
  playerIdentityId: string
}): Promise<void> {
  const gid = params.groupId.trim()
  const ck = params.conversationKey.trim()
  const pid = params.playerIdentityId.trim()
  if (!gid || !ck) return

  const group = await personaDb.getGroupChat(gid)
  if (group && group.playerIdentityId.trim() && pid && group.playerIdentityId.trim() !== pid) {
    await personaDb.rollbackMemoryAiRoundCountForRetry(ck)
    return
  }

  const cursorTs = await personaDb.getMemorySummaryCursorTimestamp(ck)
  const fromTs = (cursorTs ?? 0) + 1
  const chunkMessages = await personaDb.listWeChatChatMessagesFromTimestampAsc({
    conversationKey: ck,
    fromTimestampInclusive: fromTs,
    limit: 500,
  })

  const onlineTranscript = chunkMessagesToGroupTranscript(chunkMessages, group)
  const archiveBlock = buildGroupArchiveText(group)

  const hadOnline = onlineTranscript.length > 0
  const hadArchive = archiveBlock.trim().length > 0
  if (!hadOnline && !hadArchive) {
    await personaDb.rollbackMemoryAiRoundCountForRetry(ck)
    return
  }

  const summary = await requestGroupChatMemorySummary({
    apiConfig: params.apiConfig,
    onlineTranscript,
    groupArchiveBlock: hadArchive ? archiveBlock : '',
  })

  let trimmed = summary.trim().slice(0, 2000)
  if (!trimmed) {
    await personaDb.rollbackMemoryAiRoundCountForRetry(ck)
    return
  }

  const tagPrefix =
    `${hadOnline ? '[线上]' : ''}${hadArchive ? '[群聊]' : ''}${hadOnline || hadArchive ? ' ' : ''}`
  trimmed = tagPrefix + trimmed

  const memoryTargets =
    group?.members
      .map((m) => m.charId.trim())
      .filter(
        (cid) =>
          cid &&
          cid !== WECHAT_GROUP_USER_CHAR_ID &&
          cid !== WECHAT_GROUP_BOT_CHARACTER_ID,
      ) ?? []

  const now = Date.now()
  if (memoryTargets.length) {
    await personaDb.upsertCharacterMemory({
      id: `mem-g-${gid}-${now}-${Math.random().toString(36).slice(2, 9)}`,
      characterId: groupMemoryBucketCharacterId(gid),
      content: trimmed,
      createdAt: now,
      updatedAt: now,
      isAutoGenerated: true,
      memoryScope: 'group',
      groupId: gid,
      involvedCharIds: [...memoryTargets],
    })
  }

  if (hadOnline && chunkMessages.length) {
    const latestTs = chunkMessages[chunkMessages.length - 1]!.timestamp
    if (typeof latestTs === 'number' && Number.isFinite(latestTs)) {
      await personaDb.setMemorySummaryCursorTimestamp(ck, latestTs)
    }
  } else if (!hadOnline && hadArchive) {
    // 仅群档案、无新消息游标时仍须推进，否则会反复触发同一段总结
    await personaDb.setMemorySummaryCursorTimestamp(ck, Date.now())
  }
}
