import { emitWeChatStorageChanged, personaDb } from '../wechat/newFriendsPersona/idb'
import type { CharacterMemory } from '../wechat/newFriendsPersona/types'
import { uid } from '../wechat/newFriendsPersona/utils'
import { composeMemoryWithSourcePrefix, parseMemorySourcePrefix } from '../wechat/memory/memorySourceBadges'
import { memoryTextMatchesQuery } from '../wechat/memory/memorySearchFilter'
import { isMeetScopedCharacterMemory } from './meetClearEncounterData'
import type { EncounterMemory } from './meetTypes'

export async function loadMeetMemoriesByCharacterIds(
  charIds: string[],
): Promise<Map<string, CharacterMemory[]>> {
  const map = new Map<string, CharacterMemory[]>()
  const unique = [...new Set(charIds.map((id) => id.trim()).filter(Boolean))]
  await Promise.all(
    unique.map(async (cid) => {
      const all = await personaDb.listCharacterMemoriesForCharacter(cid)
      const meet = all.filter(isMeetScopedCharacterMemory).sort((a, b) => b.updatedAt - a.updatedAt)
      map.set(cid, meet)
    }),
  )
  return map
}

export function destinyArchiveRowMatchesQuery(
  row: EncounterMemory,
  memories: CharacterMemory[],
  query: string,
): boolean {
  const t = query.trim().toLowerCase()
  if (!t) return true
  if (row.nickname.trim().toLowerCase().includes(t)) return true
  return memories.some((m) => memoryTextMatchesQuery(m, query))
}

export async function upsertMeetArchiveMemoryEntry(params: {
  characterId: string
  body: string
  existing?: CharacterMemory | null
}): Promise<void> {
  const cid = params.characterId.trim()
  const body = params.body.trim()
  if (!cid || !body) return

  const now = Date.now()
  const flags = params.existing
    ? parseMemorySourcePrefix(params.existing.content)
    : {
        hasMeetTag: true,
        hasOnlineTag: false,
        hasGroupChatTag: false,
        hasOfflineTag: false,
        hasLinkedOfflineTag: false,
      }
  const content = composeMemoryWithSourcePrefix(
    { ...flags, hasMeetTag: true },
    body,
  ).slice(0, 4000)

  if (params.existing) {
    await personaDb.upsertCharacterMemory({
      ...params.existing,
      content,
      memoryScope: 'meet',
      updatedAt: now,
      isAutoGenerated: false,
    })
  } else {
    await personaDb.upsertCharacterMemory({
      id: uid('mem'),
      characterId: cid,
      content,
      createdAt: now,
      updatedAt: now,
      memoryScope: 'meet',
      isAutoGenerated: false,
      memoryTriggerMode: 'keyword',
    })
  }
  emitWeChatStorageChanged()
}

export async function deleteMeetArchiveMemoryEntry(id: string): Promise<void> {
  const mid = id.trim()
  if (!mid) return
  await personaDb.deleteCharacterMemory(mid)
  emitWeChatStorageChanged()
}
