import type { ApiConfig } from '../api/types'
import { personaDb } from '../wechat/newFriendsPersona/idb'
import { runUnifiedAutoMemorySummaryAfterThreshold } from '../wechat/unifiedMemoryAutoSummary'
import {
  resolvePrivateWeChatConversationKey,
  resolvePrivateWeChatStorageConversationKey,
} from '../wechat/wechatConversationKey'
import { resolvePrivateChatSessionPlayerIdentityId } from '../wechat/wechatCharacterPlayerIdentity'
import { MEET_MEMORY_CONTENT_TAG } from './meetMemoryConstants'
import type { MeetChatMessage } from './meetTypes'
import { findMeetWechatAccount, listMeetSelectableWechatAccounts } from './meetWechatAccountPool'

/** 将遇见线程全部标为已纳入自动总结游标（加好友导入微信时调用，避免与私聊游标重复总结） */
export async function advanceMeetSummaryCursorFromThread(
  characterId: string,
  thread: MeetChatMessage[],
): Promise<void> {
  const cid = characterId.trim()
  if (!cid || !thread.length) return
  const maxTs = Math.max(
    ...thread.map((m) => (typeof m.ts === 'number' && Number.isFinite(m.ts) && m.ts > 0 ? m.ts : 1)),
  )
  if (maxTs > 0) {
    await personaDb.setMeetSummaryCursorTimestamp(cid, maxTs)
  }
}

/** 若该角色已有带 `[遇见]` 的自动总结记忆，导入微信后推进私聊游标，避免把已总结过的遇见记录再送进合并总结 */
export async function alignWeChatSummaryCursorAfterMeetImport(params: {
  characterId: string
  conversationKey: string
  maxImportedTimestamp: number
}): Promise<void> {
  const cid = params.characterId.trim()
  const ck = params.conversationKey.trim()
  const maxTs = params.maxImportedTimestamp
  if (!cid || !ck || !Number.isFinite(maxTs) || maxTs <= 0) return

  const mems = await personaDb.listCharacterMemoriesForCharacter(cid)
  const hadMeetAutoSummary = mems.some(
    (m) =>
      m.isAutoGenerated &&
      (m.memoryScope === 'meet' ||
        m.content.trim().startsWith(MEET_MEMORY_CONTENT_TAG)),
  )
  if (!hadMeetAutoSummary) return

  const prev = await personaDb.getMemorySummaryCursorTimestamp(ck)
  const target = Math.floor(maxTs)
  if (prev == null || target > prev) {
    await personaDb.setMemorySummaryCursorTimestamp(ck, target)
  }
}

/**
 * 遇见临时会话每完成一轮 NPC 模型回复后调用：与私聊/约会共用 `autoSummaryInterval` 计数，
 * 达阈值后走 {@link runUnifiedAutoMemorySummaryAfterThreshold}（合并私聊 / 遇见 / 线下）。
 */
/** 与临时会话自动总结计数、邂逅档案「总结进度」展示共用 */
export async function resolveMeetAutoSummaryConversationKey(
  characterId: string,
  sessionPlayerIdentityId?: string | null,
  wechatAccountId?: string | null,
): Promise<string> {
  const cid = characterId.trim()
  const ch = await personaDb.getCharacter(cid)
  const explicit = sessionPlayerIdentityId?.trim() || ''
  const fromGlobal = (await personaDb.getCurrentIdentityId()).trim()
  const appHint = explicit || fromGlobal || null
  const acc = wechatAccountId?.trim()
  if (acc) {
    const pid = resolvePrivateChatSessionPlayerIdentityId(ch, appHint)
    return resolvePrivateWeChatStorageConversationKey(cid, acc, pid)
  }
  return resolvePrivateWeChatConversationKey(cid, ch, appHint)
}

export async function finalizeMeetCharacterMemoryRoundAfterAiReply(params: {
  apiConfig: ApiConfig | null
  characterId: string
  characterRealName: string
  sessionPlayerIdentityId?: string | null
  /** 遇见联络绑定所选微信马甲 accountId，与私聊存储键对齐 */
  meetBoundWechatAccountId?: string | null
  /** 未传 accountId 时按联络绑定微信号解析 */
  meetContactWechatId?: string | null
}): Promise<void> {
  const cid = params.characterId.trim()
  if (!cid) return

  const memSettings = await personaDb.getMemorySettings()
  if (memSettings.autoSummaryEnabled === false) return

  const explicit = params.sessionPlayerIdentityId?.trim() || ''
  const fromGlobal = (await personaDb.getCurrentIdentityId()).trim()
  const appHint = explicit || fromGlobal || null

  let boundAcc = params.meetBoundWechatAccountId?.trim() || ''
  if (!boundAcc && params.meetContactWechatId?.trim()) {
    const accounts = await listMeetSelectableWechatAccounts()
    boundAcc = findMeetWechatAccount(accounts, params.meetContactWechatId)?.accountId?.trim() || ''
  }

  const ck = await resolveMeetAutoSummaryConversationKey(cid, appHint, boundAcc || null)

  let shouldSummarizeNow = false
  try {
    const { shouldSummarize } = await personaDb.bumpMemoryAiRoundCount(ck)
    shouldSummarizeNow = shouldSummarize
    if (!shouldSummarizeNow) return
    await runUnifiedAutoMemorySummaryAfterThreshold({
      apiConfig: params.apiConfig,
      conversationKey: ck,
      characterId: cid,
      characterRealName: params.characterRealName.trim() || '对方',
      sessionPlayerIdentityId: appHint,
      wechatAccountId: boundAcc || null,
    })
  } catch (err) {
    if (shouldSummarizeNow) {
      await personaDb.rollbackMemoryAiRoundCountForRetry(ck)
    }
    console.warn('[meet-memory] auto summary failed', err)
  }
}
