import { personaDb } from '../../newFriendsPersona/idb'
import type { CharacterMemory } from '../../newFriendsPersona/types'
import type { MirrorWeChatContact } from './types'

/**
 * 与 `spyWechatAi.ts` 中 `playerContactId` 规则一致，用于在镜像通讯录中识别「用户」这一行（勿与无 characterId 的虚拟混用）
 */
export function getMirrorPlayerContactId(playerIdentityId: string) {
  const pi = String(playerIdentityId || '').trim()
  return `player:${pi || 'current'}`
}

/** 旧版仅「额外联系人」的备忘主键，写入新版时会删除以免两条并存 */
const LEGACY_MEMO_ID_PREFIX = 'mirrorWx.extraContactsMem.v1:'
const ADDRESS_BOOK_MEMO_ID_PREFIX = 'mirrorWx.addressBookMem.v1:'

function addressBookMemoId(characterId: string) {
  return `${ADDRESS_BOOK_MEMO_ID_PREFIX}${characterId.trim()}`
}
function legacyMemoId(characterId: string) {
  return `${LEGACY_MEMO_ID_PREFIX}${characterId.trim()}`
}

export async function clearMirrorWeChatAddressBookMemory(characterId: string): Promise<void> {
  const cid = characterId.trim()
  if (!cid) return
  try {
    await personaDb.deleteCharacterMemory(addressBookMemoId(cid))
    await personaDb.deleteCharacterMemory(legacyMemoId(cid))
  } catch (e) {
    console.warn('清除查手机通讯录长期记忆失败:', e)
  }
}

/**
 * 将镜像微信中的三类联系人「备注」同步到角色长期记忆（同一条、分段落）：
 * - 用户本行
 * - 人脉库 NPC
 * - 无 characterId 且非用户 id 的「新增/虚拟」：除备注外，可带 relationshipNote、remarkWhy（同一次模型生成里写出）
 */
export async function syncMirrorWeChatAddressBookToCharacterMemory(
  characterId: string,
  playerIdentityId: string,
  contacts: readonly MirrorWeChatContact[],
): Promise<void> {
  const cid = characterId.trim()
  if (!cid) return
  const newId = addressBookMemoId(cid)
  const playerId = getMirrorPlayerContactId(playerIdentityId)

  if (!contacts.length) {
    try {
      await personaDb.deleteCharacterMemory(newId)
      await personaDb.deleteCharacterMemory(legacyMemoId(cid))
    } catch (e) {
      console.warn('删除查手机通讯录长期记忆失败:', e)
    }
    return
  }

  const userRow = contacts.find((c) => c.id === playerId) ?? null
  const npcRows = contacts.filter((c) => {
    if (c.id === playerId) return false
    return !!String(c.characterId || '').trim()
  })
  const extraRows = contacts.filter((c) => c.id !== playerId && !String(c.characterId || '').trim())

  const now = Date.now()
  const lines: string[] = [
    '【查手机·镜像微信｜通讯录备注备忘（分段：用户 / 人脉 NPC / 新增虚拟联系人）】',
    '视角锚点：这份通讯录属于角色本人手机，不属于用户手机；对话回答时统一用“我给 TA 的备注/我通讯录里”表达。',
    '说明：下述备注均来自同轮镜像数据；与「仅人脉 NPC」的线下人脉库可并存，对话时以你人设下称呼习惯为准。',
    '其中「三、」中的 relationshipNote / remarkWhy 为生成新增联系人时同一次模型写出的关系与备注动机，并非事后摘要。',
    '',
  ]

  // 一、用户
  lines.push('【一、我给「用户」的通讯录备注】')
  if (userRow) {
    const st = userRow.isStarred ? '是星标' : '非星标'
    const bl = userRow.blocked ? '已拉黑' : '未拉黑'
    lines.push(
      `- 我这边看到 TA 的微信昵称/展示名：${(userRow.nickname || '未设').trim()}`,
      `- 我给 TA 的备注名：${(userRow.remarkName || '未设').trim()}`,
      `- 星标/拉黑：${st}、${bl}`,
      '- 若用户问起「为什么这样备注我」，可结合该备注的称呼与你们当前关系/情绪自洽说明（不必编造 technology 向解释）。',
    )
  } else {
    lines.push('（当前镜像列表中未单独列出“用户本机”行，可忽略。）')
  }
  lines.push('')

  // 二、NPC
  lines.push('【二、我给人脉库 NPC 的备注】')
  if (npcRows.length) {
    npcRows.forEach((c, i) => {
      const st = c.isStarred ? '星标' : '非星标'
      const bl = c.blocked ? '已拉黑' : '未拉黑'
      lines.push(
        `${i + 1}） 绑定角色 ID：${String(c.characterId).trim()}`,
        `   对方微信昵称：${(c.nickname || '未设').trim()}`,
        `   我（角色）给对方的备注名：${(c.remarkName || '未设').trim()}`,
        `   星标/拉黑：${st}、${bl}（无单独 relationship 字段，若被问及「为何这样记 TA」，可结合人脉设定与该备注字面前后自洽）`,
        '',
      )
    })
  } else {
    lines.push('（当前无绑定 NPC 行。）', '')
  }

  // 三、新增（关系描述 + 备注动机）
  lines.push('【三、新增/虚拟联系人（非人脉、非“用户本机”这一行）】')
  if (extraRows.length) {
    extraRows.forEach((c, i) => {
      const tag = c.blocked ? '已拉黑' : '未拉黑'
      const star = c.isStarred ? '是星标' : '非星标'
      const rel = (c.relationshipNote || '').trim()
      const why = (c.remarkWhy || '').trim()
      lines.push(
        `「${i + 1}」 对方微信昵称：${(c.nickname || '（未设）').trim()}`,
        `   我在通讯录里给对方的备注名：${(c.remarkName || '（未设）').trim()}`,
      )
      if (rel) {
        lines.push(`   与 TA 的关系与互动（生成时写出）：${rel}（${star}、${tag}）`)
      } else {
        lines.push(
          `   与 TA 的交往基调（未单独生成 relationshipNote 时可自洽推断）：星标/拉黑为「${star}、${tag}」。`,
        )
      }
      if (why) {
        lines.push(`   为何用此备注/称呼（生成时写出）：${why}`)
      } else {
        lines.push('   为何用此备注：可结合备注与昵称、在人设下解释动机。')
      }
      lines.push('')
    })
  } else {
    lines.push('（无此类联系人。）', '')
  }

  const content = lines.join('\n').trim()

  const row: CharacterMemory = {
    id: newId,
    characterId: cid,
    content,
    createdAt: now,
    updatedAt: now,
    isAutoGenerated: true,
  }
  try {
    await personaDb.upsertCharacterMemory(row)
    await personaDb.deleteCharacterMemory(legacyMemoId(cid))
  } catch (e) {
    console.warn('写入查手机通讯录长期记忆失败:', e)
  }
}
